---
name: Example CI Workflow

'on':
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run basic tests
        run: |
          echo "Running basic validation tests"
          echo "Repository structure check passed"

      - name: Validate workflow syntax
        run: |
          echo "Workflow syntax validation completed"
